kind: Deployment
apiVersion: apps/v1
metadata:
  name: kitchensink-db
  labels:
    app: kitchensink-db
    app.kubernetes.io/component: kitchensink-db
    app.kubernetes.io/instance: kitchensink-db
    app.kubernetes.io/part-of: kitchensink-app
    app.openshift.io/runtime: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: kitchensink-db
      app: kitchensink-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: kitchensink-db
        app: kitchensink-db
    spec:
      containers:
        - name: kitchensink-db
          image: >-
            centos/postgresql-10-centos7:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kitchensink-database-secret
                  key: DB_NAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kitchensink-database-secret
                  key: DB_PASSWORD
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: kitchensink-database-secret
                  key: DB_USERNAME
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false

